name: psxmpc
description: A new jardam Classified application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+8
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  platform: ^3.1.0
  shared_preferences: 2.0.18
  http: 0.13.5
  provider: 6.0.5
  connectivity: 3.0.6
  # connectivity_plus: 3.0.3
  cached_network_image: 3.2.3
  theme_manager: 1.1.1
  flutter_map: 3.1.0
  image_picker: ^0.8.6+4
  latlong2: 0.8.1

  sembast: 3.4.0+6
  path_provider: 2.0.13
  intl: 0.17.0
  shimmer: 2.0.0
  url_launcher: 6.1.10
  carousel_slider: 4.2.1
  
  firebase_core: 1.20.1
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: 11.0.0
  firebase_database: 7.2.1 #stick with this version, upgraded versions has issue(top message disappearing)
  firebase_auth: 3.11.2
  # webview_flutter: 2.1.2
  google_mobile_ads : 2.3.0
  google_sign_in: 6.0.1
  flutter_facebook_auth: 4.0.0
  photo_view: 0.14.0  
  progress_dialog_null_safe: 1.0.7
  flutter_braintree: 3.0.0
  launch_review: 3.0.1
  package_info_plus: 1.4.3

  flutter_credit_card: 3.0.5
  fluttertoast: 8.2.1
  permission_handler: 10.2.0 
  permission_handler_platform_interface: ^3.9.0
  geocode: 1.0.2
  geolocator: 9.0.2 
  flutter_html: 2.2.1
  share_plus: 6.3.1
  the_apple_sign_in: 1.1.1
  razorpay_flutter: 1.3.4
  flutter_native_image: 0.0.6+1
  flutter_paystack: 1.0.7
  firebase_dynamic_links: 4.3.4
  in_app_purchase: 3.1.5
  flutter_linkify: 5.0.2
  google_maps_flutter: 2.2.4
  flutter_datetime_picker: 1.5.1
  video_thumbnail: 0.5.3
  video_player: 2.5.2
  file_picker: 5.2.5
  geocoding: 2.0.5
  camera: 0.10.3+2
  app_tracking_transparency: 2.0.3 
  firebase_crashlytics: 2.8.8
  map_launcher: 2.5.0+1
  device_info_plus: 8.1.0
  platform_device_id: 1.0.1
  encrypt: 5.0.1
  dotted_border: <2.0.0+3
  flutter_stripe: 8.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
 
 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/lang/
   - assets/images/placeholder_circle_image.png
   - assets/images/placeholder_image.png
   - assets/images/flutter_buy_and_sell_logo.png
   - assets/images/default_image.png
   - assets/images/user_default_photo.png
   - assets/images/location_onboard.svg
   - assets/images/slider_1.svg
   - assets/images/slider_2.svg
   - assets/images/slider_3.svg
   - assets/images/no_notification.svg
   - assets/images/buy_package.svg
   - assets/images/onboard_language.svg
   - assets/images/chat_list_empty_photo.svg
   - assets/images/demo_alert.png 
   - assets/images/google_logo.png 
   - assets/images/buy_package_background.png
   - assets/images/item_list_empty.svg
   - assets/images/facebook.svg
   - assets/images/google.svg
   - assets/images/instagram.svg
   - assets/images/pinterest.svg
   - assets/images/twitter.svg
   - assets/images/youtube.svg
   - assets/images/home_bottom.svg
   - assets/images/home_bottom_selected.svg
   - assets/images/payment/offline.png
   - assets/images/payment/paypal.png
   - assets/images/payment/paystack.png
   - assets/images/payment/razor.png
   - assets/images/payment/stripe.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ps_standard_font
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


